development:
  adapter: "intersys"
  namespace: "HM"
  package: "HM"
  host: "192.168.168.171"
  port: "1972"
  user: "_system"
  password: "SYS"

production:
  adapter: "intersys"
  namespace: "HM"
  package: "HM"
  host: "192.168.168.171"
  port: "1972"
  user: "_system"
  password: "SYS"

